const CACHE_NAME="mushimusume-v29-hatch-quote-layout-fix";
const ASSETS=[
  "./README.md",
  "./app.js",
  "./assets/characters/beetle_1.png",
  "./assets/characters/beetle_2.png",
  "./assets/characters/beetle_3.png",
  "./assets/characters/beetle_4.png",
  "./assets/characters/butterfly_1.png",
  "./assets/characters/butterfly_2.png",
  "./assets/characters/butterfly_3.png",
  "./assets/characters/butterfly_4.png",
  "./assets/characters/mantis_1.png",
  "./assets/characters/mantis_2.png",
  "./assets/characters/mantis_3.png",
  "./assets/characters/mantis_4.png",
  "./assets/eggs/beetle_egg.png",
  "./assets/eggs/butterfly_egg.png",
  "./assets/eggs/mantis_egg.png",
  "./assets/enemies/angry_hornet.png",
  "./assets/enemies/aphid_swarm.png",
  "./assets/enemies/jueki/bark_longhorn.png",
  "./assets/enemies/jueki/long_blade_longhorn.png",
  "./assets/enemies/jueki/mud_weevil.png",
  "./assets/enemies/jueki/night_moth.png",
  "./assets/enemies/jueki/sap_ants.png",
  "./assets/enemies/jueki/yokozuna_hanamuguri.png",
  "./assets/enemies/night_stag.png",
  "./assets/enemies/old_nest_spider.png",
  "./assets/enemies/rotten_centipede.png",
  "./assets/enemies/territorial_bee.png",
  "./assets/enemies/web_spider.png",
  "./assets/icons/icon-192.png",
  "./assets/icons/icon-512.png",
  "./assets/relics/beetle_1.png",
  "./assets/relics/beetle_2.png",
  "./assets/relics/beetle_3.png",
  "./assets/relics/cicada_1.png",
  "./assets/relics/cicada_2.png",
  "./assets/relics/cicada_3.png",
  "./assets/relics/jueki/bark_jaw_1.png",
  "./assets/relics/jueki/bark_jaw_2.png",
  "./assets/relics/jueki/bark_jaw_3.png",
  "./assets/relics/jueki/five_soul_2.png",
  "./assets/relics/jueki/poison_scales_1.png",
  "./assets/relics/jueki/poison_scales_2.png",
  "./assets/relics/jueki/poison_scales_3.png",
  "./assets/relics/mantis_1.png",
  "./assets/relics/mantis_2.png",
  "./assets/relics/mantis_3.png",
  "./index.html",
  "./manifest.webmanifest",
  "./style.css",
  "./sw.js"
];
self.addEventListener("install",e=>{e.waitUntil(caches.open(CACHE_NAME).then(c=>c.addAll(ASSETS)).then(()=>self.skipWaiting()))});
self.addEventListener("activate",e=>{e.waitUntil(caches.keys().then(keys=>Promise.all(keys.map(k=>k!==CACHE_NAME?caches.delete(k):null))).then(()=>self.clients.claim()))});
self.addEventListener("fetch",e=>{
  const url=new URL(e.request.url);
  const freshFirst=["document","script","style"].includes(e.request.destination)||url.pathname.endsWith(".html")||url.pathname.endsWith(".js")||url.pathname.endsWith(".css");
  if(freshFirst){
    e.respondWith(fetch(e.request).then(res=>{const copy=res.clone(); caches.open(CACHE_NAME).then(c=>c.put(e.request,copy)); return res;}).catch(()=>caches.match(e.request)));
    return;
  }
  e.respondWith(caches.match(e.request).then(c=>c||fetch(e.request)));
});
